### PR TITLE
add save filter config

### PR DESCRIPTION
**Pull request by xuliefeng**
add undo list by save filter config

### CODE REVIEW

**Comment by debugloop** [comment]
Hi, thanks for your contribution, but I don't quite follow what the idea is here, sorry... 

In either case, as a first step I'd ask you to add some documentation to the README in either case, maybe that'll shed some light 👍🏻

**Review by debugloop — CHANGES_REQUESTED** [review]
Please add documentation to the README.

**Comment by xuliefeng** [comment]
Sorry, English is not very good. What I want to express is to add a configuration to the displayed results to ignore the data displayed without saving the write

```lua
require("telescope").setup({
  extensions = {
    undo = {
       save = true, -- filter item is save flag result, hide not write buf value
    },
  },
})
```

**Comment by debugloop** [comment]
Ah, I think I'll got it 👍🏻 I'll go ahead and write some docs for it sometime this month 👍🏻

**Comment by debugloop** [comment]
Sorry I took so long, but I merged your changes in today 🎉

I've however made a mistake during the `Co-Authored-By` so now the commit is not correctly attributed to you, I am very sorry 💔 I tried so salvage by merging this PR as an "empty" PR, but Github does not allow that.

I can't rebase `main`, as people might already have pulled your commit (that is not correctly attributed to you...).

**Comment by debugloop** [comment]
I salvaged it with an empty commit: https://github.com/debugloop/telescope-undo.nvim/commit/a3dcb6e32a3a59a5570a7cda33171eeef9753345

I think it'll add you to the contributors list as well. I hope that's fine by you 👍🏻

**Pull request closed without merging**
